### ISSUE TITLE
Undefined symbols for architecture arm64 _Firebase_Auth_Credential_IsValid

### ISSUE THREAD

**Issue by SeanLangre** [firebase/quickstart-unity#1031]
### [REQUIRED] Please fill in the following fields:

Unity editor version: 2018.4.28f1
Firebase Unity SDK version: 7.0.2
Source you installed the SDK: UPM
Problematic Firebase Component: FirebaseAuth
Other Firebase Components in use: FirebaseDatabase, FirebaseAnalytics
Additional SDKs you are using: Facebook, Google Play Games
Platform you are using the Unity editor on: Windows
Platform you are targeting: iOS, Android
Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Xcode build fail when we try to use this code in our project:
FirebaseAccountLinkException.UserInfo.UpdatedCredential.IsValid()

There are no errors in the Unity Editor and it fails even if we never run the code, only if it exists. If we remove the code, everything works, our users can sign in and access everything that we have built with Firebase.

```
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/pocappstudios/Documents/gc_UnityBuilds/gc-178-test-stickerss/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_Firebase_Auth_Credential_IsValid", referenced from:
      _AuthUtilPINVOKE_Firebase_Auth_Credential_IsValid_m9F811DD2B524BA867CB26E7740886BC8D67CFBC5 in Bulk_Firebase.Auth_0.o
      _Credential_IsValid_mF86E2CC93C68DAEB48564FC0FED4257A0D69AC1E in Bulk_Firebase.Auth_0.o
     (maybe you meant: _AuthUtilPINVOKE_Firebase_Auth_Credential_IsValid_m9F811DD2B524BA867CB26E7740886BC8D67CFBC5)
  "_Firebase_Auth_AdditionalUserInfo_UpdatedCredential_get", referenced from:
      _AdditionalUserInfo_get_UpdatedCredential_mBEEA016B2B779C24F32AB741861522B656BC3378 in Bulk_Firebase.Auth_0.o
      _AuthUtilPINVOKE_Firebase_Auth_AdditionalUserInfo_UpdatedCredential_get_m2BE5AC825E34780F7B4213C2813A628556D9D8A0 in Bulk_Firebase.Auth_0.o
     (maybe you meant: _AuthUtilPINVOKE_Firebase_Auth_AdditionalUserInfo_UpdatedCredential_get_m2BE5AC825E34780F7B4213C2813A628556D9D8A0)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Steps to reproduce:

Use FirebaseAccountLinkException.UserInfo.UpdatedCredential.IsValid() in your code and try to build in Xcode. We do not even call the function.

We have not tried with Firebase Unity quickstarts (this GitHub project).

We do not have a downloadable sample project right now.

**Comment by paulinon** [comment]
Hi @SeanLangre,

Could you try updating the SDK to version 7.1.0 and see if this resolves the issue? If not, I'd like you to provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates this issue so that we can verify if this is a bug. 

Thanks.

**Comment by SeanLangre** [comment]
It did not work on version 7.1.0 either. I'll try creating a small minimal, reproducible example that demonstrates the issue.
