### ISSUE TITLE
Unable to build project for iOS platform with Firestore 6.15.1

### ISSUE THREAD

**Issue by vzlomvl** [firebase/quickstart-unity#726]
### Please fill in the following fields:
Unity editor version: 2018.4.23
Firebase Unity SDK version: 6.15.1
Source you installed the SDK (.unitypackage or Unity Package Manager): Unity Package Manager
Firebase plugins in use (Auth, Database, etc.): Firestore, Auth
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): iOS
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
After update to 6.15.1 version of Firebase, I am unable to build my project to iOS platform. When I am trying to build project in Xcode I see an error:
`Undefined symbols for architecture arm64:
  "firebase::firestore::api::Firestore::Dispose()", referenced from:
      firebase::firestore::FirestoreInternal::~FirestoreInternal() in libFirebaseCppFirestore.a(firestore_ios_eec52dfa6e1434eb3ea69ba309362c0c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
Steps to reproduce with a new project:
1 Create a new empty project
2 Add Dependency to the Firestore and Auth 6.15.1 with Unity Package Manager
3 Create a script with reference to Firestore. For example FirebaseFirestore.DefaultInstance.
4 Build Unity project for iOS platform
5 Try to build Xcode project (Run or Archive)
6 See an error
Steps to reproduce with the attached project:
1 Open the project
2 Build Unity project for iOS platform
3 Try to build Xcode project (Run or Archive)
4 See an error

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
I haven't tried to reproduce with quickstarts but I am able to reproduce with an empty project with Firesotre dependency.
I have attached a project on which you can reproduce the issue(just build an Xcode project and press Run or Archive).     
[TestFirestore.zip](https://github.com/firebase/quickstart-unity/files/4863393/TestFirestore.zip)

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

**Comment by vzlomvl** [comment]
Sorry, looks like the issue was already reported.
https://github.com/firebase/quickstart-unity/issues/725
