### ISSUE TITLE
Generation of the Firebase Android resource file google-services.xml from Assets/Plugins/google-services.json failed.

### ISSUE THREAD

**Issue by karry-phone** [firebase/quickstart-unity#551]
### Please fill in the following fields:
Unity editor version:  2019.2.10f1
Firebase Unity SDK version: 6.9.0 (use dotNet45)
Firebase plugins in use (Auth, Database, etc.): Analytics
Additional SDKs you are using (Facebook, AdMob, etc.): AdMob 4.2.1
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows 7
Platform you are targeting (iOS, Android, and/or desktop): iOS and Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
When I upgrade from 6.6.0 to 6.9.0, it causes this problem:
Generation of the Firebase Android resource file google-services.xml from Assets/Plugins/google-services.json failed.
If you have not included a valid Firebase Android resources in your app it will fail to initialize.
"D:\MyProject\Assets\Firebase\Editor\generate_xml_from_google_services_json.exe" -i "Assets/Plugins/google-services.json" -l

Traceback (most recent call last):
  File "<string>", line 446, in <module>
  File "<string>", line 289, in main
  File "<string>", line 228, in argv_as_unicode_win32
AttributeError: 'module' object has no attribute 'wintypes'
generate_xml_from_google_services_json returned -1

You can start to diagnose this issue by executing ""D:\MyProject\Assets\Firebase\Editor\generate_xml_from_google_services_json.exe" -i "Assets/Plugins/google-services.json" -l" from the command line.
UnityEngine.Debug:LogError(Object)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:RunResourceGenerator(IEnumerable`1, String, Boolean) (at Z:/tmp/tmp.4EPdOx77tp/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:527)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:ReadBundleIds(String) (at Z:/tmp/tmp.4EPdOx77tp/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:394)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:UpdateConfigFileDirectory() (at Z:/tmp/tmp.4EPdOx77tp/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:282)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:CheckConfiguration() (at Z:/tmp/tmp.4EPdOx77tp/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:233)
Firebase.Editor.GenerateXmlFromGoogleServicesJson:<GenerateXmlFromGoogleServicesJson>m__0() (at Z:/tmp/tmp.4EPdOx77tp/firebase/app/client/unity/editor/src/GenerateXmlFromGoogleServicesJson.cs:98)
Google.RunOnMainThread:ExecuteNext() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:377)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:408)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

Yes. I create a new empty project. Copy GoogleService-Info.plist and google-services.json of MyProject to /Assets/Plugins of this new project. Then import FirebaseAnalytics.unitypackage and the problem is reproduced.

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

I know there is a issue #540 , but it maybe different. Because there is not any "Python" in my log.

**Comment by paulinon** [comment]
Hi @karry-phone Could you try installing this package and see if the issue persists? https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=29

**Comment by karry-phone** [comment]
After install this package, the problem still exists.

**Comment by paulinon** [comment]
Duplicate of #540
