### ISSUE TITLE
Error when building Unity project to Xcode (arm64 function not 4-byte aligned)

### ISSUE THREAD

**Issue by Nicokkam** [firebase/quickstart-unity#898]
[REQUIRED] Please fill in the following fields:

Unity editor version: _____2020.1.0f1
Firebase Unity SDK version: _____Latest
Source you installed the SDK: _____ .unitypackage
Problematic Firebase Component: _____ Database
Other Firebase Components in use: _____ Auth, Database and Analytics
Additional SDKs you are using: _____ Facebook
Platform you are using the Unity editor on: _____ Mac
Platform you are targeting: _____ iOS, Android
Scripting Runtime: _____ IL2CPP

[REQUIRED] Please describe the issue here:

I am using firebase SDK's in my project. I made the Email/Password authentication to work and the next step was to implement Facebook SignIn. Everything worked fine and it seems to be working, given that there are no errors in the console and I followed all of the documentation steps. The problem starts when building the project and trying to run it through Xcode.

I read everything regarding similar errors and nothing solved it. The error I am getting is:

Showing Recent Messages
Undefined symbol: OBJC_CLASS$_GKLocalPlayer

ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/XXX/XXX/XXX/XXX/YYYY/Build_iOS/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
"OBJC_CLASS$GKLocalPlayer", referenced from:
objc-class-ref in libFirebaseCppAuth.a(credential_ios XXX.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[EDIT]
One thing I noticed is that when I run "pod --version" within the "Build_iOS" folder, it returns 1.10.0.

**Comment by Vah94** [comment]
d: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/username/Documents/IOS_Builds/AppName/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GKLocalPlayer", referenced from:
      objc-class-ref in libFirebaseCppAuth.a(credential_ios_7e32949a14fe9694040ff5eed8d1b954.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Nicokkam** [comment]
Does anyone have information on this subject? 

I'm stuck with this problem for almost a day without being able to solve it. Would appreciate some help!

**Comment by hlorenzo93** [comment]
I have exactly the same error since I updated to 7.0.1, and I have googled the whole day and cannot find a solution.

**Comment by GilbertoBitt** [comment]
OMG, is nice and sad to hear we all have the same problem.

**Comment by Nicokkam** [comment]
I found a fix!

Just follow the instructions provided by @snorrsi in this thread.

https://github.com/facebook/facebook-sdk-for-unity/issues/504
